### ISSUE TITLE
Coming Soon

### ISSUE THREAD

**Issue by MoodyLass** [MoodyLass/Teacup#2]
Splash Landing pages load to sub-doms for links in index.

**Comment by sudo-self** [comment]
The changes involve removing a large amount of code that seems to be related to Microsoft Word formatting and settings. The code includes meta elements, link elements, and XML tags that are specific to Microsoft Word document properties and settings.These elements are not required in an HTML webpage and are typically added automatically when saving a Word document as
HTML.
