### ISSUE TITLE
Shoppe

### ISSUE THREAD

**Issue by MoodyLass** [MoodyLass/Teacup#3]
Deploy the eCommerce Shoppe.

**Comment by sudo-self** [comment]
CNAME will need DNS to propagate
shoppe.domains.payhip.com

resolving

https://shoppe.moodylass.com/

**Comment by sudo-self** [comment]
Here are some iframe examples, thats the only thing I see broken in your code. 


This is an external website iframe example


<iframe <iframe=“" src="https://PICTURE OF CAT.jpg" width="660px" height="450" frameborder="0"></iframe>


Instead you can put all the pictures in a folder named “ASSETS” then point to it internally with href=


<iframe <iframe=“" href=“/ASSETS/PICTURE OF CAT.jpg” 

src="https://yourdomain.com/ASSETS/PICTURE OF CAT.jpg" width="660px" height="450" frameborder="0"></iframe>



Then taking it a step further you can place a complete website in a folder “project 1”

index.html
style.css
script.js


Then use and an iframe or <a> tag to link “project 1”

<a href=“yourdomain.com/project 1" src=“https://yourdomain.com/project 1”</a>


src is the actual picture while href is where the item is in an iframe or what happens on mouse click in a hyperlink.



Its how my entire GitHub Page is set up


Almost every repo is a template feel free to use them as needed. And the attached html is a 4 iframe examples 






￼











￼
